### PR TITLE
Add GitHub Actions workflow

### PR DESCRIPTION
**Pull request by thethiny**
Whenever any .py file gets updated, a new release is automatically deployed. The only thing missing here is the names `db3` file which you can push somewhere and have it be pulled.

### CODE REVIEW

**Comment by bnnm** [comment]
Looks good overall but may be better to update a nightly release rather than new+tag instead. Another manual job could make a new tagged/proper release instead, or I can keep doing it manually I guess.

Main reason I don't do new releases often is that testing isn't easy and wwiser wonky/complex, so new changes "work" but are kind of wip until I try some more games or encounter edge cases. Plus the userbase is minuscule so new releases for minor typos/doc feel kind of silly.

**Comment by bnnm** [comment]
Thanks, I think buidling to a nightly release would be preferable since it allows me to decide when a release is "stable", plus having "numbered"/tagged releases on every commit feels kind of intimidating.

For reference in vgmstream I made a [fixed release](https://github.com/vgmstream/vgmstream-releases/releases/tag/nightly) that a [script](https://github.com/vgmstream/vgmstream/blob/master/.github/uploader.py) updates but there is probably an easier/cleaner way to achieve that, but I didn't delve into it too much.

**Comment by thethiny** [comment]
@bnnm I have added 2 workflows, Nightly and Stable, and have tested both on https://github.com/thethiny/wwiser/tree/test_actions as [nightly](https://github.com/thethiny/wwiser/actions/runs/9198788726) and [stable](https://github.com/thethiny/wwiser/actions/runs/9198788724).

Let me know if it's something you like or if you want to modify it further, or simply abort the idea altogether.

**Comment by bnnm** [comment]
At a glance looks good but give me some more time until I review and understand the implications.

(but basically I prefer a model like [duckstation](https://github.com/stenzek/duckstation/releases) with one nightly rather than [pcsx2](https://github.com/PCSX2/pcsx2/releases) with many micro releases)

**Comment by thethiny** [comment]
> but basically I prefer a model with one nightly rather than many micro releases
I've done that in which you can see [here](https://github.com/thethiny/wwiser/releases/tag/latest-nightly). It is one nightly tagged as `latest-nightly`, but whenever there's a new nightly it just **renames** the previous nightly to the new one, so you only end up with 1 nightly at a time.

**Comment by bnnm** [comment]
Wanted to do some local tests but guess I'll just accept this and see how it goes, can always be tweaked later.

**Comment by thethiny** [comment]
@bnnm I hope this can be useful to you. If you encounter any issues or behavior changes please let me know so I can update that for you 👍🏻

**Pull request merged**
